[[redirects]]
  from = "*"
  to = "http://183.99.247.17:8881/api/*"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  command = "npm run build"
  publish = "build"

[context.production.environment]
  Token = "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpZCI6NTI2LCJleHAiOjE2NDUyNjA0NTQsImVtYWlsIjoic2VjdXJpdHlUZXN0QHNhdmxlLmNvbSJ9.iSPvXDEnap4AtcWWcixAINifhnaiSB15UwH7Jr4qkrGFQFlBbArnGZ2Z0LbhBiV7Cih6tkPQeOF29GbtGVYR1w"
